yiisoft/yii2-debug

CHANGELOG.md
assets/toolbar.css

| Breaks BC?    | I hope not
| Tests pass?   | n/a
| Fixed issues  | #120 
The height when closed was 42px, the height when open was auto,
which evaluated to 40px, causing the toolbar to jump up 2 pixels
when closed.
There's no need to have a 42px height on the outer element,
since the inner element has a 40px height.
There's no need to explicitly set the height to auto either.
Fixes #120

Remove heights from toolbar

---

CHANGELOG.md
Panel.php
views/default/panels/log/summary.php

The 'error' and 'warning' counters on the summary bar 'deeplink' to their respective filters avoiding unnecessary clicks and reloads when looking for the specific log type. Example: http://prntscr.com/co7ctj

Added 'deeplinking' to log level type

---

CHANGELOG.md
Module.php
composer.json
tests/ModuleTest.php

Extracted from https://github.com/yiisoft/yii2/issues/12726
`yii\debug\Module::defaultVersion()` implemented to pick up 'yiisoft/yii2-debug' extension version

`yii\debug\Module::defaultVersion()` implementation

---

CHANGELOG.md
Module.php
Panel.php
README.md
docs/guide/installation.md
tests/PanelTest.php
tests/bootstrap.php
views/default/panels/db/detail.php
views/default/panels/log/detail.php

Added ability to config the trace file and line number

---

CHANGELOG.md
assets/toolbar.css

- When iframe is opened the toggle arrow is directed down. It shows a direction of panel moving.
- When the debug panel is collapsed the toggle arrow is directed right and when the panel is opened the toggle arrow is directed left. It shows a wrong direction of panel moving.

toogle button direction fix

---

panels/UserPanel.php

I noticed that my user panel was display a blank page because $attributes was coming up as an empty array. This should handle ActiveRecord models properly
| New feature?  | no minor update
| Tests pass?   | not sure...
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

Display ActiveRecord data in UserPanel if applicable

---

panels/UserPanel.php

If set attribute in User model as callback, then we have Exception at  https://github.com/yiisoft/yii2-debug/blob/master/LogTarget.php#L57
`'Serialization of 'Closure' is not allowed' `
| Fixed issues  |  #195

Fix Serialization of Closure error

---

CHANGELOG.md
panels/UserPanel.php

This PR combines some code cleanup (1ad7fa57fe00fc3f1a5b8c68b0d2b4d3033b2630, 9234be7cfcb1291b8293aefe417802510f13db3f) and a bit of refactoring on how the `identity` and `attributes` User panel data keys get defined, making it easier for subclasses to customize (ac1dcb73df001b5b4bfdcf9c5b9e53ef08508c8d).

Cleanup + identity packaging enhancements

---

CHANGELOG.md
assets/toolbar.css
views/default/toolbar.php

Fix to remove toolbar from print page via [css-bootsrap](http://getbootstrap.com/css/#responsive-utilities-print)

Enh: To remove toolbar when PRINT MODE ON

---

CHANGELOG.md
assets/toolbar.css

Prevents the toolbar from jumping up during the animation,
which is caused by the animating width not being enough to hold
all the elements.
If the fully open toolbar can't hold everything in one line,
the toolbar will still jump up after the animation is done,
but it's less jarring than before.
Fixes #223
| Is bugfix?    | yey
| Tests pass?   | n/a
| Fixed issues  | #223

Limit the height during the opening animation

---

CHANGELOG.md
views/default/panels/db/detail.php

Fix triple-click on copy db queries from debug panel (db section) in [firefox browser](https://en.wikipedia.org/wiki/Triple-click#Firefox_3.5)

Fix triple-click via firefox

---

CHANGELOG.md
panels/AssetPanel.php

| Tests pass?   | uncovered but should pass
| Fixed issues  | #242
Details in https://github.com/yiisoft/yii2-debug/issues/242. Related to app structures not implementing HTML or assets like REST apps.

Fixes #242 by omitting AssetsPanel creation when yii/web/AssetManager not being used

---

CHANGELOG.md
models/UserSwitch.php
views/default/panels/user/detail.php
views/default/panels/user/summary.php

Fixes #251: User panel was displaying current user info instead of user info at the moment of request

---

CHANGELOG.md
panels/UserPanel.php
views/default/panels/user/summary.php

| Breaks BC?    | yes
| Fixed issues  | #262

Fixes #262: Fixed issue when identity ID is stored in a field different from `id`

---

CHANGELOG.md
panels/UserPanel.php
views/default/panels/user/summary.php

| Tests pass?   | ?
| Fixed issues  | #265

Fixed calling `isMainUser()` on null regression in 2.0.10

---

CHANGELOG.md
panels/UserPanel.php

When using multiple yii\web\Users with different idParams, the session regeneration (which is forced by isGuest) will destroy the session.
| Is bugfix?    | yes & no

Do not force session regeneration

---

CHANGELOG.md
panels/RequestPanel.php
views/default/panels/request/detail.php

This PR adds a new “General Info” table on the Request panel (Parameters tab).
The table displays the following Request values:
- `method`
- `isAjax`
- `isPjax`
- `isFlash`
- `isSecureConnection`
While technically everything here could be determined by looking at other Request panel info, none of it is obvious, as there is logic that goes into these getter methods based on HTTP headers, etc.
We found ourselves needing this, especially the `isSecureConnection` row, when working to update our project for the new secure headers feature in Yii 2.0.13. Having that info readily available should save others some time.

General Info table on Request panel

---

CHANGELOG.md
Module.php

| Fixed issues  | #302 
@samdark I've tested this with any suffixes from UrlManager and it works great. I don't know - is it a good solution to turn off suffix for debug panel always, but seems like it always doesn't need it.

Fixes #302: Debug panel with suffix

---

CHANGELOG.md
src/assets/toolbar.css

This style fix should limit the width of wide labels, prevents formation of multiple lines in toolbar
Before:
After:
it's just proposed, maybe we can find some better way to optimize this view

prevent multiple lines in toolbar

---

src/views/default/toolbar.php

not super relevant, but I noticed it when activating a CSS style to higlight images without alt tag on my site.
| Fixed issues  | n/a

Added alt tag to debug toolbar image

---

CHANGELOG.md
src/assets/toolbar.js

Fixes #327: set the active class before setting display:block

---

CHANGELOG.md
src/panels/LogPanel.php

`yii\log\Target` can sometimes set a message without the `trace` (`index=4`) element in the array, eg:
https://github.com/yiisoft/yii2/blob/master/framework/log/Target.php#L128
```
if (($context = $this->getContextMessage()) !== '') {
$this->messages[] = [$context, Logger::LEVEL_INFO, 'application', YII_BEGIN_TIME];
}
```
| Fixed issues  | #332

fix error when trace is missing from message

---

CHANGELOG.md
src/Module.php
src/panels/DumpPanel.php
src/views/default/panels/dump/detail.php
src/views/default/panels/dump/summary.php

| Is bugfix?    | ❌ 
| New feature?  | ✔️ 
| Breaks BC?    | ❌ 
| Tests pass?   | ✔️ 
| Fixed issues  | PR #309, #247 
Working demo: [http://demo.karlen.li/web/](http://demo.karlen.li/web/debug/default/view?panel=dump&tag=5c065aa07d5e9)
Debug calling controller code:
```php
/**
* Displays homepage.
*
* @return string
*/
public function actionIndex()
{
Yii::debug([
'test' => 'value',
'foo' => 'bar',
'bar' => 'baz'
]);
Yii::debug(null);
$std = new \stdClass();
$std->null = null;
$std->test = 'value';
$std->integer = 22;
$std->float = 3.2521553;
$std->boolean = false;
$std->array = [
'test' => 'value',
'foo' => 'bar',
'null' => null,
'integer' => 33,
'float' => 3.2521553,
'boolean' => false
];
Yii::debug($std);
return $this->render('index');
}
```

added PR #309 dump panel

---

CHANGELOG.md
src/panels/MailPanel.php

When mails fail to serialize all debug panels break due to the summary.
This is shown for a panel that is not the mail panel:
```php
PHP Warning 'yii\base\ErrorException' with message 'count(): Parameter must be an array or an object that implements Countable' 
in /project/vendor/yiisoft/yii2-debug/src/panels/MailPanel.php:111
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'count(): Parame...', '/project/vendor...', 111, Array)
#1 /project/vendor/yiisoft/yii2-debug/src/panels/MailPanel.php(111): count(NULL)
#2 /project/vendor/yiisoft/yii2-debug/src/views/default/view.php(25): yii\debug\panels\MailPanel->getSummary()
#3 /project/vendor/yiisoft/yii2/base/View.php(348): require('/project/vendor...')
#4 /project/vendor/yiisoft/yii2/base/View.php(257): …
```

Fix panel display when mails fail to serialize.

---

CHANGELOG.md
composer.json
src/LogTarget.php
src/Panel.php
src/controllers/DefaultController.php
src/panels/DumpPanel.php
src/panels/LogPanel.php
tests/FlattenExceptionTest.php

| Is bugfix?    | kinda
| New feature?  | kinda
| Breaks BC?    | maybe?
| Fixed issues  | #390 
The only BC breaking change was removing the `$stringify` parameter for `Panel::getLogMessages()` that I introduced in 2.1.4.

Enh #390 Better serializer (incl. closures) by using opis/closure

---

CHANGELOG.md
src/LogTarget.php
src/Panel.php
src/panels/DumpPanel.php
src/panels/LogPanel.php
src/views/default/panels/dump/detail.php

| Tests pass?   | yes (probably need some more)
| Fixed issues  | #401 
Partial revert of #398, so the log panel will work correctly.  The dump panel will now format the object before it is serialized and save that string instead, which is much safer.

Fix #401 SPL object closure

---

CHANGELOG.md
src/views/default/panels/log/detail.php

Due to differences in how DateInterval::format() works in different PHP versions we need to replace it for simple math.
| Fixed issues  | #409

Fixes in "Since previous" column's value calculation

---

CHANGELOG.md
src/views/default/panels/log/detail.php

| Fixed issues  | #412 
Before:
After:
Closes #412

Improve layout for the Logs panel

---

CHANGELOG.md
src/views/default/index.php
src/views/default/view.php

When `document.domain` is set for cross-origin reasons, `window.frameElement` can return `null`.
Comparing `window.top` to `window` is safe, as when both objects are same it is no iframe.
https://developer.mozilla.org/en-US/docs/Web/API/Window/frameElement
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Changing_origin

Duplicate toolbar bugfix

---

CHANGELOG.md
src/views/default/view.php
src/widgets/NavigationButton.php

| New feature?  | ✔️
| Fixed issues  | #202 
Single request:
First active request:
"Middle" active request:
Last active request:

Fix #202: add buttons for navigation between requests

---

CHANGELOG.md
src/assets/js/timeline.js

In earlier version the code was using foreach which created the link variable, current code uses a for loop.

Fixes missing variable link

---

CHANGELOG.md
src/panels/DumpPanel.php

| Fixed issues  | 
I don't know how it was working without importing class:
https://github.com/yiisoft/yii2-debug/blob/3faaa0d6a8ee7592f23f0962496773d1d9ead0b0/src/panels/DumpPanel.php#L120
Can be tested with:
```php
$panel = new DumpPanel([
'highlight' => false,
]);
$panel->varDump('');
```
but I'm not sure that the tests needs to be written for that.

Fix import yii\helpers\Html in DumpPanel

---

src/models/router/ActionRoutes.php
tests/router/ActionRoutesTest.php
tests/router/controllers/RedirectController.php

Ok, last try. This time controllers are not initialized at all in order to avoid calling any method to prevent any additional extra stuff that can be done there. Unfortunately this makes scanning `actions()` not possible (at least I cannot find a way to do it without using some extra code parsers or something similar) so I'm just leaving it mentioned.

Initiating controllers take 3

---

CHANGELOG.md
src/Module.php
tests/ModuleTest.php

| New feature?  | ✔️
This PR adds support for CIDR ranges in allowedIPs, which is especially useful for docker (which uses class B ranges by default).

Add CIDR support for allowedIPs

---

CHANGELOG.md
src/Module.php

Added the ability to change logTarget, now it's hard code class.
```php
$config['modules']['debug'] = [
'class' => 'yii\debug\Module',
'allowedIPs' => ['*'],
'logTarget' => \common\components\DebugLogTarget::class // nothing affects
];
```
| Fixed issues  | none

Fix inability to change LogTarget

---

src/panels/UserPanel.php

If the UserPanel class member variable `$this->filterModel` is NULL, php 8.1 will complain and throw a deprecation error. 
I am adding an is_null() check before the class_exists call to fix this
```
PHP Deprecated Warning – yii\base\ErrorException
class_exists(): Passing null to parameter #1 ($class) of type string is deprecated
```
| Fixed issues  | #473

Fixes 8.1 issue: class_exists with null value will error

---

CHANGELOG.md
src/views/default/panels/db/detail.php
src/views/default/panels/log/detail.php
src/views/default/panels/profile/detail.php

I've been unable to open the logs, profiling, and database panels on PHP 8.1, which greet me with a deprecation notice:
This PR intends to resolve such issue.
| Fixed issues  | #470

Fix PHP 8.1 warning (implicit conversion from float to int loses precision)

---

CHANGELOG.md
src/Module.php
tests/ModuleTest.php

| Fixed issues  | #481
Fixes _slight_ BC break introduced by PR #469.

Fix #481: only init logTarget if it's not already

---

CHANGELOG.md
src/views/default/index.php
src/views/default/panels/db/summary.php

| Fixed issues  | #503 
With this PR exceeding the "critical query threshold" and/or "excessive callers" will no longer be displayed as an error in the debug panel. Only a "⚠" is displayed.

Reduce db panel warnings for "critical query threshold" and "excessive callers"

---

CHANGELOG.md
docs/guide/db-panel.md
src/panels/DbPanel.php
src/views/default/panels/db/callers.php
src/views/default/panels/db/summary.php

Correctly handle `null` values for `DbPanel::$criticalQueryThreshold` and `::$excessiveCallerThreshold`

---

CHANGELOG.md
src/assets/js/toolbar.js

When the toolbar scripts are loaded in case of bundled with other scripts, but the toolbar html is not present on the page any xhr / fetch calls fails on https://github.com/yiisoft/yii2-debug/blob/master/src/assets/js/toolbar.js#L325 with error `"Cannot read properties of null (reading 'getAttribute')"`

Check if toolbar element is found on the page before access it

---

CHANGELOG.md
src/Panel.php
src/views/default/index.php
src/views/default/panels/log/detail.php

It should be noted that if an internal php function such as call_user_func in the backtrace, the 'file' and 'line' entries will not be set.
@see  https://www.php.net/manual/en/function.debug-backtrace.php#59713

If an internal PHP function, such as `call_user_func`, in the backtrace, the 'file' and 'line' not be available.

---

src/models/router/RouterRules.php

I assume this was a typo, since it's the only case statement using the non-standard syntax.

Fix inconsistent switch case syntax

---

src/panels/UserPanel.php

This fixes an issue where backticks cause a shell command to be executed instead of creating a string with a FQCN.
The backticks are replaced by quotes.
| Fixed issues  |  None

Fixed backticks used instead of single quotes.

---

CHANGELOG.md
src/assets/js/toolbar.js

| Fixed issues  | 
In cases when `fetch(...)` results in an error (for example, a network issue or the request is aborted), allow the call site to choose whether to ignore the error, or handle it. As the the toolbar has a separate promise chain, that the call site has no access to, rethrowing the error causes unnecessary noise in console logs when the error has already been handled by the call site.
This separate promise chain is not used after updating the `stackElement` array, so its safe to not rethrown error.
**Before:**
* Unhandled errors log _two_ messages in console 
* Handled errors log _one_ message in console
**After:**
* Unhandled errors log _one_ message in console 
* Handled …

Silence fetch errors
