views/default/index.php
Fix class label of bootstrap (http://getbootstrap.com/components/#available-variations)
Before : 
After :
=> Fix class label [skip ci]

views/default/toolbar.php
For correct displaying on sites with cp1251 encoding
=> unicode symbols changed to html characters

CHANGELOG.md, panels/LogPanel.php
=> avoid serializing php7 errors

CHANGELOG.md, Module.php, controllers/DefaultController.php
| Breaks BC?    | yes
| Fixed issues  | #115
=> Issue #115 Make default panel configurable and set it to log

CHANGELOG.md, Module.php, TimelineAsset.php, assets/timeline.css, assets/timeline.js, components/TimelineDataProvider.php, components/search/matchers/GreaterThanOrEqual.php, models/search/Timeline.php, panels/TimelinePanel.php, views/default/panels/timeline/detail.php, views/default/panels/timeline/summary.php
| Breaks BC?    | yes
| Fixed issues  | #58
=> Profiling timeline #58

CHANGELOG.md, assets/toolbar.css, assets/toolbar.js
| Tests pass?   | n/a
| Fixed issues  | 
This fixes https://github.com/yiisoft/yii2-debug/pull/147#issuecomment-251955685
#147 should be merged first.
=> Remove transition property when not needed.

CHANGELOG.md, assets/toolbar.css, views/default/toolbar.php
| Fixed issues  | no issue, direct PR
fixes toolbar to be responsive
=> Fix responsive height

README.md
The parameter is incorrect config
=> The parameter is incorrect config

docs/guide/topics-creating-your-own-panels.md
| Is bugfix?    | yes/no
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Fix classes for debug panel sample

CHANGELOG.md, LogTarget.php, tests/LogTargetTest.php
=> Fixes #179: Increased request time logging accuracy and precision

CHANGELOG.md, Module.php, composer.json, models/Router.php, panels/LogPanel.php, panels/RouterPanel.php, views/default/panels/router/detail.php
=> Routing panel

CHANGELOG.md, Module.php, panels/UserPanel.php, views/default/panels/user/detail.php, views/default/panels/user/summary.php
| Fixed issues  | #181
any suggestions?
=> WIP : initial commit

CHANGELOG.md, Module.php, tests/ModuleTest.php, views/default/panels/mail/detail.php
| Tests pass?   | yes/no
| Fixed issues  | none
=> Use module's real ID instead of hardcoded "debug"

panels/UserPanel.php, views/default/panels/user/detail.php
=> Fixes small issues

CHANGELOG.md, panels/UserPanel.php
…ntains non-string data
| Fixed issues  | #200
=> Fixed error in user panel when RBAC role or permission contains non-string data

CHANGELOG.md, models/timeline/Svg.php, views/default/panels/timeline/detail.php
| Tests pass?   | ---
| Fixed issues  | #221
=> Timeline. Fixed the decimal point.

README.md
Update the Readme with instructions about allowing IPs for debugging
=> Add a comment about allowedIPs

CHANGELOG.md, panels/UserPanel.php
=> Fixes #249: Fixed toolbar not displayed because of misconfigured authManager

CHANGELOG.md, assets/toolbar.js
=> Catch fetch AJAX requests

CHANGELOG.md, panels/UserPanel.php
=> Fixes #257: Fixed user panel to properly display object attributes

CHANGELOG.md, panels/RequestPanel.php, views/default/panels/request/detail.php
=> Fixes #188: Added `RequestPanel::$displayVars` that lists allowed variables in request panel

CHANGELOG.md
=> Added release date in changelog

README.md, docs/guide/installation.md
=> Add documentation for traceLine, Fixes #175

CHANGELOG.md, Module.php
=> Always show debug headers

CHANGELOG.md, assets/toolbar.js
=> fix fetch request profile link

CHANGELOG.md, assets/toolbar.js
=> Fetch with request param

.travis.yml, CHANGELOG.md, composer.json, models/timeline/Svg.php
=> PHP 7.2 compatibility

CHANGELOG.md, models/search/Db.php, panels/DbPanel.php, views/default/panels/db/detail.php
=> Duplicated queries count on DB panel #281

CHANGELOG.md, src/Module.php
=> [ENH] Added confguration option to toggle IP address restriction warning on / off

CHANGELOG.md, src/LogTarget.php, src/panels/MailPanel.php
=> Fixes #300: Fixed email files are not deleted by GC

CHANGELOG.md, src/panels/RequestPanel.php, src/views/default/panels/timeline/detail.php
PJax is dropped in 2.1
| Fixed issues  | https://github.com/yiisoft/yii2-debug/issues/313
=> remove pJax

src/LogTarget.php
=> Fixes #321: Fixed invalid argument in GC

README.md
=> Add example for dockerized advanced template to PHPStorm

CHANGELOG.md, src/views/default/panels/user/detail.php
| Is bugfix?    | ✔️ 
| New feature?  | ❌ 
| Breaks BC?    | ❌ 
| Tests pass?   | ✔️ 
| Fixed issues  | #343
=> fixed bug #343 (fixed var name to $items)

CHANGELOG.md, src/Module.php
| Is bugfix?    | ❌ 
| New feature?  | ✔️ 
| Breaks BC?    | ❌ 
| Tests pass?   | ✔️ 
| Fixed issues  | #88
=> Allow custom module access check (enh #88)

CHANGELOG.md, src/assets/js/toolbar.js
Fixes #342
| Fixed issues  | #342
=> Disable animation whilst debug bar is opening (fixes #342)

CHANGELOG.md, src/Module.php, src/models/Router.php, src/panels/RouterPanel.php, src/views/default/panels/request/summary.php, src/views/default/panels/router/summary.php
| New feature?  | yes/no
| Breaks BC?    | yes/no
| Tests pass?   | yes/no
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
=> Fixed router panel link

CHANGELOG.md, src/assets/js/toolbar.js
| Fixed issues  | #298
block links & iframe focusability is now toggled depending on the debug bar state
=> Fix keyboard navigation when bar is collapsed/hidden

CHANGELOG.md, src/Module.php, src/views/layouts/main.php
| Fixed issues  | https://github.com/yiisoft/yii2-debug/issues/353
=> Dynamic html view title #353

src/Panel.php
=> Add missing import

CHANGELOG.md, docs/guide/topics-creating-your-own-panels.md, src/assets/js/toolbar.js
=> Allow better toolbar interaction

README.md, docs/guide-ja/installation.md, docs/guide/installation.md
=> Fixes #392: Better example of traceLine paths in dockerized environment

.travis.yml, CHANGELOG.md, src/controllers/DefaultController.php
=> Fixes #379: Unable to find debug data tagged with ''.

CHANGELOG.md, src/views/default/view.php
=> Fixed escaping in views

.travis.yml, CHANGELOG.md, src/Module.php, src/assets/js/db.js, src/assets/js/timeline.js, src/assets/js/userswitch.js, src/views/default/panels/user/switch.php
| Is bugfix?    | ✔️ 
| New feature?  | ❌ 
| Breaks BC?    | ❌ 
| Tests pass?   | ✔️ 
| Fixed issues  | #347, #333
=> Fixed #347, #333 and updated js / travis config

docs/guide-ja/topics-creating-your-own-panels.md
| Tests pass?   | --
| Fixed issues  | --
=> docs/guide-ja/topics-creating-your-own-panels.md updated [skip ci]

.travis.yml
=> Add PHP 7.4 to travis CI

CHANGELOG.md, src/LogTarget.php
=> Fix #325: remove obsoleted files

CHANGELOG.md, src/assets/js/toolbar.js
=> Fix #329: track AJAX request with explicitly defined scheme

CHANGELOG.md, src/views/default/panels/db/detail.php
| New feature?  | ✔️
| Fixed issues  | #425
=> Enhancements on db panel related to traceLevel as per issue #425

docs/guide-ja/installation.md
| Tests pass?   | --
| Fixed issues  | --
=> docs/guide-ja/installation.md updated [ci skip]

CHANGELOG.md, src/models/router/ActionRoutes.php, tests/router/ActionRoutesTest.php, tests/router/module/Module.php, tests/router/module/controllers/ModuleWebController.php
=> Fixed bug with rule name

.github/workflows/build.yml, CHANGELOG.md, tests/FlattenExceptionTest.php
| Fixed issues  | #441 
https://www.php.net/manual/en/migration74.other-changes.php#migration74.other-changes.ini
=> 441 flatten exception

CHANGELOG.md, src/models/router/ActionRoutes.php, tests/router/ActionRoutesTest.php, tests/router/controllers/WebController.php
=> Fix for simple class action detection

CHANGELOG.md, src/models/router/ActionRoutes.php, src/panels/RouterPanel.php, tests/router/ActionRoutesTest.php, tests/router/controllers/BadController.php
| Breaks BC?    | ✔️ (but I think it won't be a problem here)
| Fixed issues  | #449
=> Fix bug with scanned controllers being unnecessary initiated

src/models/router/ActionRoutes.php, tests/router/ActionRoutesTest.php, tests/router/controllers/RedirectController.php
=> Instantiating controller in case actions() must be scanned

.github/SECURITY.md
| Tests pass?   | ~
| Fixed issues  | just a typo
=> Fix typo [skip ci]

CHANGELOG.md, src/panels/MailPanel.php
Fix for issue #507
Explicitly convert headers to string
| Fixed issues  |  507
=> Update MailPanel.php fixes #507

docs/guide-es/installation.md, docs/guide-ja/installation.md, docs/guide-uk/installation.md, docs/guide-zh-CN/installation.md, docs/guide/installation.md
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-debug/issues/521
=> update docs folder links

src/assets/scss/bs-4.3.1/_print.scss, src/panels/UserPanel.php
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | resolve https://github.com/yiisoft/yii2-debug/issues/524
=> update src folder links

.editorconfig, .github/workflows/build.yml, composer.json, phpunit.xml.dist, tests/FlattenExceptionTest.php, tests/LogTargetTest.php, tests/ModuleTest.php, tests/PanelTest.php, tests/TestCase.php
=> Use Yii2 `2.2`.

composer.json
| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
=> Fix branch alias in `composer.json` for `dev-22`.

composer.json
=> Remove branch alias for `dev-22` from `composer.json`.
